//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПракктическаяРабота17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейсы_аэрофлот
    {
        public string Номер_рейса { get; set; }
        public string Пункт_назначения { get; set; }
        public Nullable<System.TimeSpan> Время_вылета { get; set; }
        public Nullable<System.TimeSpan> Время_прибытия { get; set; }
        public int Количество_свободных_мест { get; set; }
        public string Тип_самолета { get; set; }
        public Nullable<int> Вместимость { get; set; }
    }
}
